name: Apply Manifests

on: 
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options: [run-all, skip-terraform]
        default: run-all
  push:
    branches:
      - master

jobs:
  job1: 
    if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'skip-terraform') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        run: echo "hello world"


        


        
