name: Apply Manifests


on: 
  workflow_dispatch: {}
  push:
    branches:
      - master

  

jobs:
  job1: 
    runs-on: self-hosted
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: Apply Manifests
        run: kubectl apply -f manifests/


        


        
