name: First Workflow


on: 
  workflow_dispatch: {}
  push: {}

  

jobs:
  first-job: 
    runs-on: self-hosted
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: Print greeting
        run: kubectl apply -f manifests/


        


        
